version: '3'

services:
  front:
    build:
      context: .
      dockerfile: cmd/front/Dockerfile
    env_file:
      - cmd/front/local.env
    ports:
      - "5000:5000"
    depends_on:
      - updater
      - redis
  updater:
    build:
      context: .
      dockerfile: cmd/updater/Dockerfile
    env_file:
      - cmd/updater/local.env
    ports:
      - "5001:5001"
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
    driver: local
