# version: '3'
# services:
#   web:
#     build: .
#     volumes:
#       - ./:/go/src/github.com/Scalingo/sclng-backend-test-v1
#     ports:
#       - "5000:5000"
#     command: reflex -r '\.go$$' -s -- sh -c 'go build -buildvcs=false && ./sclng-backend-test-v1'
#     stop_signal: SIGKILL

version: '3'

services:
  updater:
    build:
      context: .
      dockerfile: cmd/updater/Dockerfile
    env_file:
      - cmd/updater/local.env
    ports:
      - "5001:5001"
    depends_on:
      - redis
      # - db
  # db:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'
  #   volumes: 
  #     - db-data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
    driver: local
  # db-data:
  #   driver: local
